#!/usr/bin/env python3
"""Package an exact NumPy wasm static-built-in payload and runtime manifest."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[2]
NATIVE_PAYLOAD_PATH = PLUGIN_ROOT / "package/editor/infernux_web/native_payload.py"
_NATIVE_PAYLOAD_SPEC = importlib.util.spec_from_file_location(
    "_infernux_web_native_payload", NATIVE_PAYLOAD_PATH
)
if _NATIVE_PAYLOAD_SPEC is None or _NATIVE_PAYLOAD_SPEC.loader is None:
    raise RuntimeError(f"cannot load Web native payload helpers: {NATIVE_PAYLOAD_PATH}")
_NATIVE_PAYLOAD = importlib.util.module_from_spec(_NATIVE_PAYLOAD_SPEC)
_PREVIOUS_DONT_WRITE_BYTECODE = sys.dont_write_bytecode
sys.dont_write_bytecode = True
try:
    _NATIVE_PAYLOAD_SPEC.loader.exec_module(_NATIVE_PAYLOAD)
finally:
    sys.dont_write_bytecode = _PREVIOUS_DONT_WRITE_BYTECODE

WEB_NUMPY_SOURCE_SHA256 = _NATIVE_PAYLOAD.WEB_NUMPY_SOURCE_SHA256
WEB_NUMPY_SOURCE_URL = _NATIVE_PAYLOAD.WEB_NUMPY_SOURCE_URL
WEB_NUMPY_VERSION = _NATIVE_PAYLOAD.WEB_NUMPY_VERSION
WEB_NUMPY_BUILTIN_MODULES = _NATIVE_PAYLOAD.WEB_NUMPY_BUILTIN_MODULES
python_package_payload_identity = _NATIVE_PAYLOAD.python_package_payload_identity

EXPECTED_MODULES = WEB_NUMPY_BUILTIN_MODULES

_NON_RUNTIME_DIRECTORY_NAMES = frozenset({"__pycache__", "test", "tests"})
_NON_RUNTIME_FILE_SUFFIXES = frozenset({".pyc", ".pyo", ".pyi"})


def _module_name(path: Path, site_packages: Path) -> str:
    relative = path.relative_to(site_packages)
    stem = relative.name.split(".", 1)[0]
    return ".".join((*relative.parent.parts, stem))


def _read_records(record_dir: Path) -> dict[Path, dict[str, object]]:
    records: dict[Path, dict[str, object]] = {}
    for path in sorted(record_dir.glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        if document.get("schema") != "infernux.numpy_static_link.v1":
            raise ValueError(f"invalid NumPy static link record: {path}")
        output = Path(str(document.get("output", ""))).resolve()
        if output in records:
            raise ValueError(f"duplicate NumPy static link record: {output}")
        records[output] = document
    return records


def _registry(modules: tuple[str, ...]) -> str:
    declarations = []
    registrations = []
    for module in modules:
        symbol = "PyInit_" + module.rsplit(".", 1)[-1]
        if not re.fullmatch(r"PyInit_[A-Za-z_][A-Za-z0-9_]*", symbol):
            raise ValueError(f"invalid built-in initializer symbol: {symbol}")
        declarations.append(f"PyMODINIT_FUNC {symbol}(void);")
        registrations.append(
            f'    if (PyImport_AppendInittab("{module}", &{symbol}) == -1) return -1;'
        )
    return (
        "/* Generated by prepare_numpy_static_payload.py; do not edit. */\n"
        "#include <Python.h>\n\n"
        + "\n".join(declarations)
        + "\n\n#ifdef __cplusplus\nextern \"C\"\n#endif\n"
        + "int InfernuxRegisterNumPyBuiltins(void)\n{\n"
        + "\n".join(registrations)
        + "\n    return 0;\n}\n"
    )


def _reject_links(root: Path) -> None:
    if root.is_symlink() or not root.is_dir():
        raise ValueError(f"expected a real directory: {root}")
    for path in root.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"input tree contains a symlink: {path}")


def _prune_non_runtime_python_files(package_root: Path) -> None:
    """Remove build/test metadata which CPython never needs at runtime."""

    directories = sorted(
        (
            path
            for path in package_root.rglob("*")
            if path.is_dir() and path.name.casefold() in _NON_RUNTIME_DIRECTORY_NAMES
        ),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    for directory in directories:
        shutil.rmtree(directory)
    for path in tuple(package_root.rglob("*")):
        if path.is_file() and path.suffix.casefold() in _NON_RUNTIME_FILE_SUFFIXES:
            path.unlink()


def _validate_runtime_python_files(package_root: Path) -> None:
    forbidden: list[str] = []
    for path in package_root.rglob("*"):
        relative = path.relative_to(package_root).as_posix()
        if any(part.casefold() in _NON_RUNTIME_DIRECTORY_NAMES for part in path.parts):
            forbidden.append(relative)
        elif path.is_file() and path.suffix.casefold() in _NON_RUNTIME_FILE_SUFFIXES:
            forbidden.append(relative)
    if forbidden:
        raise ValueError(
            "non-runtime Python files remain in Web NumPy payload: "
            + ", ".join(sorted(forbidden)[:12])
        )


def _copy_dependency_archive(
    source: Path,
    destination: Path,
    *,
    archiver: Path | None,
    numpy_build_root: Path,
) -> None:
    """Copy a regular archive or materialize a relocatable copy of a thin archive."""

    with source.open("rb") as stream:
        magic = stream.read(8)
    if magic != b"!<thin>\n":
        shutil.copyfile(source, destination)
        return
    if archiver is None or archiver.is_symlink() or not archiver.is_file():
        raise ValueError(f"thin dependency archive requires an explicit archiver: {source}")
    listing = subprocess.run(
        [str(archiver), "t", str(source)],
        cwd=source.parent,
        check=True,
        capture_output=True,
        text=True,
    )
    members: list[Path] = []
    for item in listing.stdout.splitlines():
        member = Path(item)
        if not member.is_absolute():
            member = source.parent / member
        if member.is_symlink():
            raise ValueError(f"thin archive member must not be a symlink: {item}")
        resolved = member.resolve()
        if (
            not resolved.is_file()
            or not resolved.is_relative_to(numpy_build_root)
        ):
            raise ValueError(f"invalid thin archive member: {item}")
        members.append(resolved)
    if not members:
        raise ValueError(f"thin dependency archive is empty: {source}")
    subprocess.run(
        [str(archiver), "rcsD", str(destination), *(str(path) for path in members)],
        check=True,
    )
    with destination.open("rb") as stream:
        materialized_magic = stream.read(8)
    if materialized_magic != b"!<arch>\n":
        raise ValueError(f"dependency archive was not materialized: {source}")


def prepare(
    install_root: Path,
    record_dir: Path,
    numpy_build_root: Path,
    cpython_build_root: Path,
    output_root: Path,
    *,
    archiver: Path | None = None,
) -> Path:
    _reject_links(install_root)
    _reject_links(record_dir)
    _reject_links(numpy_build_root)
    _reject_links(cpython_build_root)
    if output_root.exists() or output_root.is_symlink():
        raise ValueError(f"output must not already exist: {output_root}")
    candidates = [
        path for path in install_root.rglob("site-packages")
        if (path / "numpy").is_dir()
    ]
    if len(candidates) != 1:
        raise ValueError("NumPy install must contain exactly one site-packages tree")
    site_packages = candidates[0]
    extensions = sorted((site_packages / "numpy").rglob("*.so"))
    module_paths = {_module_name(path, site_packages): path for path in extensions}
    if len(module_paths) != len(extensions) or set(module_paths) != set(EXPECTED_MODULES):
        missing = sorted(set(EXPECTED_MODULES) - set(module_paths))
        extra = sorted(set(module_paths) - set(EXPECTED_MODULES))
        raise ValueError(f"NumPy extension closure mismatch; missing={missing}, extra={extra}")
    records = _read_records(record_dir)
    records_by_stem: dict[str, list[tuple[Path, dict[str, object]]]] = {}
    for record_path, record in records.items():
        records_by_stem.setdefault(record_path.name.split(".", 1)[0], []).append(
            (record_path, record)
        )
    extension_records: dict[str, dict[str, object]] = {}
    consumed_records: set[Path] = set()
    for module, path in module_paths.items():
        matches = records_by_stem.get(path.name.split(".", 1)[0], [])
        if len(matches) != 1:
            raise ValueError(f"missing static link record for {module}: {path}")
        record_path, record = matches[0]
        consumed_records.add(record_path)
        extension_records[module] = record
    output_root.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output_root.name}.", dir=output_root.parent))
    try:
        payload = staging / "payload"
        package_target = payload / "site-packages/numpy"
        shutil.copytree(site_packages / "numpy", package_target)
        for extension in package_target.rglob("*.so"):
            extension.unlink()
        _prune_non_runtime_python_files(package_target)
        _validate_runtime_python_files(package_target)
        forbidden = [p for p in package_target.rglob("*") if p.suffix in {".so", ".wasm"}]
        if forbidden:
            raise ValueError("dynamic Web payload files remain: " + ", ".join(map(str, forbidden)))

        archive_target = payload / "archives"
        archive_target.mkdir()
        dependency_by_digest: dict[str, str] = {}
        for module in EXPECTED_MODULES:
            source = module_paths[module]
            shutil.copyfile(source, archive_target / f"{module}.a")
            dependencies = extension_records[module].get("dependency_archives")
            if not isinstance(dependencies, list):
                raise ValueError(f"invalid dependency archive record for {module}")
            for item in dependencies:
                dependency = Path(str(item))
                if dependency.is_symlink() or not dependency.is_file():
                    raise ValueError(f"missing dependency archive for {module}: {dependency}")
                resolved = dependency.resolve()
                if resolved.is_relative_to(cpython_build_root):
                    continue
                if not resolved.is_relative_to(numpy_build_root):
                    raise ValueError(
                        f"unclassified external dependency archive for {module}: {dependency}"
                    )
                digest = hashlib.sha256(dependency.read_bytes()).hexdigest()
                if digest not in dependency_by_digest:
                    name = f"dependency-{digest[:16]}-{dependency.name}"
                    _copy_dependency_archive(
                        dependency,
                        archive_target / name,
                        archiver=archiver,
                        numpy_build_root=numpy_build_root,
                    )
                    dependency_by_digest[digest] = name

        (payload / "numpy_builtin_registry.c").write_text(
            _registry(EXPECTED_MODULES), encoding="utf-8", newline="\n"
        )
        archive_names = [f"archives/{module}.a" for module in EXPECTED_MODULES]
        archive_names += [f"archives/{dependency_by_digest[key]}" for key in sorted(dependency_by_digest)]
        (payload / "numpy_static_link.json").write_text(
            json.dumps(
                {
                    "schema": "infernux.numpy_static_payload.v1",
                    "modules": list(EXPECTED_MODULES),
                    "archives": archive_names,
                    "registry": "numpy_builtin_registry.c",
                    "preload": "site-packages",
                },
                indent=2,
                sort_keys=True,
            ) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        identity = python_package_payload_identity(payload)
        runtime = {
            "implementation": "cpython",
            "version": "3.13.15",
            "abi": "cp313",
            "platform": "emscripten",
            "platform_version": "4.0.10",
            "architecture": "wasm32",
            "extension_linkage": "static-built-in",
            "required_imports": ["numpy"],
            "packages": [{
                "name": "numpy",
                "version": WEB_NUMPY_VERSION,
                "imports": ["numpy"],
                "python_abi": "cp313",
                "platform": "emscripten",
                "platform_version": "4.0.10",
                "architecture": "wasm32",
                "linkage": "static-built-in",
                "source_url": WEB_NUMPY_SOURCE_URL,
                "source_sha256": WEB_NUMPY_SOURCE_SHA256,
                "payload_hash_algorithm": identity["algorithm"],
                "payload_sha256": identity["sha256"],
                "payload_bytes": identity["bytes"],
                "payload_files": identity["files"],
                "license": "BSD-3-Clause",
            }],
        }
        (staging / "runtime-manifest.json").write_text(
            json.dumps(runtime, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        os.replace(staging, output_root)
        return output_root
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install-root", required=True, type=Path)
    parser.add_argument("--record-dir", required=True, type=Path)
    parser.add_argument("--numpy-build-root", required=True, type=Path)
    parser.add_argument("--cpython-build-root", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--archiver", required=True, type=Path)
    options = parser.parse_args()
    prepare(
        options.install_root.resolve(),
        options.record_dir.resolve(),
        options.numpy_build_root.resolve(),
        options.cpython_build_root.resolve(),
        options.output_root.resolve(),
        archiver=options.archiver.resolve(),
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"prepare-numpy-static-payload: {error}", file=sys.stderr)
        raise SystemExit(1)
